### ISSUE TITLE
In the Delivery Pipeline, the deploy section does not have dropdown to choose from

### ISSUE THREAD

**Issue by l2fprod** [IBM-Bluemix/logistics-wizard-toolchain#10]
In the simple toolchain example (https://github.com/open-toolchain/simple-toolchain) the Delivery Pipeline section looks like:

![image](https://cloud.githubusercontent.com/assets/12746550/18204084/175e9fa8-711b-11e6-935b-84f7a97e981e.png)

But in our toolchain, it looks like:

![image](https://cloud.githubusercontent.com/assets/12746550/18204057/f04eb588-711a-11e6-9cbe-09135dc2a6a1.png)

Why? This is based on https://github.com/open-toolchain/toolchain-demo. It basically hides the individual region/org/space configuration of the underlying git projects, and shows a custom UI to pick region/org/space. However this custom UI does not benefit from the dropdown making it error prone to select region/org/space.

**Comment by rvennam** [comment]
Surprised that fixed it..
