### ISSUE TITLE
Investigate splitting the Delivery Pipeline in two to build master and dev separately

### ISSUE THREAD

**Issue by l2fprod** [IBM-Bluemix/logistics-wizard-toolchain#14]
The current Delivery Pipeline builds the dev and the master branches. However there is no link between the two as they both build from the source in Git.

A typical pipeline would look like:
[DEV-BUILD]  -> [DEV-DEPLOY] -> [BUILD] -> [DEPLOY]
which creates confusion as it makes it sound like DEV-DEPLOY triggers BUILD.

An option would be to create one delivery pipeline per branch, each with its own "build & deploy" flow. It should be easier to understand and more scalable if one wants to add a pipeline for a new branch as example.

Aim of this issue is to try this approach on the logistics-controller module as example to understand the impact.

**Comment by l2fprod** [comment]
changed the webui in https://github.com/IBM-Bluemix/logistics-wizard-toolchain/tree/split-dev-and-master

![image](https://cloud.githubusercontent.com/assets/12746550/18873796/68f7fecc-84c1-11e6-9751-7d9a72fa1f53.png)

multiple pipelines work as expected.
all builds are started.

however we might need to use a shorter name for the pipeline so that DEV and PROD labels are visible.

also given we create more pipelines than repositories we have more "deliver" than "think" or "code" boxes so there is no horizontal alignment - there was before but this was not by design.

**Comment by l2fprod** [comment]
split all pipelines

![image](https://cloud.githubusercontent.com/assets/12746550/18876032/6964fcb4-84c8-11e6-8bac-864684cc4cb3.png)

**Comment by rvennam** [comment]
Much better!

**Comment by rvennam** [comment]
merged with #16
