### ISSUE TITLE
Update Toolchain readMe

### ISSUE THREAD

**Issue by Twanawebtech** [IBM-Bluemix/logistics-wizard-toolchain#25]
When deploying this using Toolchain user must change the host name to something unique, this is messing from the readMe. https://github.com/IBM-Bluemix/logistics-wizard-toolchain

Add a quick note to users that they must change the host names in order for the build to deploy successfully.

**Comment by l2fprod** [comment]
added a comment in the README.

However the real fix needs to come from the toolchain to check for unique names right from the Delivery Pipeline panel as done by the Deploy To Bluemix button.

And even if we put more random names by using the toolchain name generated by the wizard (as shown here https://github.com/IBM-Bluemix/insurance-toolchain/issues/8), the user could still end up with existing names.
