### ISSUE TITLE
Only build one branch

### ISSUE THREAD

**Issue by l2fprod** [IBM-Bluemix/logistics-wizard-toolchain#34]
Just like what has been done for Cloud Insurance, add fields to select the name of the branch to build from each repository.

This will lead to a smaller footprint for the overall demo.

**Comment by van-ibm** [comment]
Added the execute: false property to the dev pipelines in the toolchain. This will result in dev pipelines not running after toolchain creation, which will limit deployed applications and services to just production. Readme has been updated to reflect behavior. Will be merged from feature/optional-pipelines onto master.
