### ISSUE TITLE
Create Toolchain button broken

### ISSUE THREAD

**Issue by rvennam** [IBM-Bluemix/logistics-wizard-toolchain#5]
Results in:

> Sorry…
> 
> Cannot read template from repo https://github.com/IBM-Bluemix/logistics-wizard-toolchain.git and branch master

**Comment by l2fprod** [comment]
@rvennam 

I can deploy the toolchain successfully from the "Create Toolchain" button.

**Comment by rvennam** [comment]
Seems like it was a temporary bug.
